title: Block Lists
description: Categorized blocklists for security and compliance purposes
theme: jekyll-theme-cayman
baseurl: "/block_poc"
url: ""
markdown: kramdown
permalink: /:title.html
include:
  - .nojekyll
exclude:
  - .git
  - Gemfile
  - Gemfile.lock
defaults:
  - scope:
      path: ""
    values:
      layout: "default"